CREATE TABLE `audit_ledger` (
CREATE TABLE `comments` (
CREATE TABLE `custody_wallets` (
CREATE TABLE `dating_blocks` (
CREATE TABLE `dating_likes` (
CREATE TABLE `dating_matches` (
CREATE TABLE `dating_messages` (
CREATE TABLE `dating_notifications` (
CREATE TABLE `dating_preferences` (
CREATE TABLE `dating_profiles` (
CREATE TABLE `dating_reports` (
CREATE TABLE `dating_subscriptions` (
CREATE TABLE `follows` (
CREATE TABLE `fraud_signals` (
CREATE TABLE `governance_proposals` (
CREATE TABLE `governance_votes` (
CREATE TABLE `likes` (
CREATE TABLE `messages` (
CREATE TABLE `moderation_logs` (
CREATE TABLE `notifications` (
CREATE TABLE `on_chain_transactions` (
CREATE TABLE `orders` (
CREATE TABLE `platform_metrics` (
CREATE TABLE `posts` (
CREATE TABLE `products` (
CREATE TABLE `rate_limit_buckets` (
CREATE TABLE `reviews` (
CREATE TABLE `streams` (
CREATE TABLE `token_balances` (
CREATE TABLE `token_emission_caps` (
CREATE TABLE `token_market_state` (
CREATE TABLE `transactions` (
CREATE TABLE `user_archetypes` (
CREATE TABLE `user_behavior_signals` (
CREATE TABLE `users` (
CREATE TABLE `wallet_audit_log` (
CREATE TABLE `wallet_transactions` (
CREATE TABLE `wallets` (
