/**
 * 1-Click Server Installer Engine
 * Generates Docker Compose, env files, install scripts, and health checks
 */

import crypto from "crypto";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface InstallerConfig {
  projectName: string;
  domain: string;
  adminEmail: string;
  dbPassword: string;
  jwtSecret: string;
  redisPassword: string;
  enableSSL: boolean;
  enableRedis: boolean;
  enableNginx: boolean;
  port: number;
}

export interface GeneratedFiles {
  dockerCompose: string;
  envFile: string;
  nginxConfig: string;
  installScript: string;
  readmeSetup: string;
}

export interface HealthCheckResult {
  service: string;
  status: "healthy" | "degraded" | "down";
  latency: number;
  message: string;
}

// ─── Env Generator ───────────────────────────────────────────────────────────

export function generateEnvFile(config: InstallerConfig): string {
  const jwtSecret = config.jwtSecret || crypto.randomBytes(32).toString("hex");
  const dbPassword = config.dbPassword || crypto.randomBytes(16).toString("hex");
  const redisPassword = config.redisPassword || crypto.randomBytes(16).toString("hex");

  return `# ShadowChat / SKYCOIN4444 Environment Configuration
# Generated by Server Installer Engine
# DO NOT commit this file to version control

# ── App ──────────────────────────────────────────────────────────────────────
NODE_ENV=production
PORT=${config.port || 3000}
APP_DOMAIN=${config.domain || "localhost"}
ADMIN_EMAIL=${config.adminEmail || "admin@example.com"}

# ── Database ─────────────────────────────────────────────────────────────────
DATABASE_URL=mysql://shadowchat:${dbPassword}@db:3306/shadowchat
DB_PASSWORD=${dbPassword}

# ── Auth ─────────────────────────────────────────────────────────────────────
JWT_SECRET=${jwtSecret}
SESSION_SECRET=${crypto.randomBytes(32).toString("hex")}

# ── Redis ────────────────────────────────────────────────────────────────────
REDIS_URL=redis://:${redisPassword}@redis:6379
REDIS_PASSWORD=${redisPassword}

# ── Storage (S3-compatible) ───────────────────────────────────────────────────
S3_BUCKET=shadowchat-media
S3_REGION=us-east-1
S3_ACCESS_KEY=your_access_key_here
S3_SECRET_KEY=your_secret_key_here
S3_ENDPOINT=https://s3.amazonaws.com

# ── Stripe ───────────────────────────────────────────────────────────────────
STRIPE_SECRET_KEY=sk_live_your_key_here
STRIPE_WEBHOOK_SECRET=whsec_your_secret_here
VITE_STRIPE_PUBLISHABLE_KEY=pk_live_your_key_here

# ── AI / LLM ─────────────────────────────────────────────────────────────────
OPENAI_API_KEY=your_openai_key_here
ANTHROPIC_API_KEY=your_anthropic_key_here

# ── Crypto ───────────────────────────────────────────────────────────────────
SKY444_CONTRACT_ADDRESS=0x...
TREASURY_WALLET=0x...

# ── Monitoring ───────────────────────────────────────────────────────────────
SENTRY_DSN=https://your_sentry_dsn_here
LOG_LEVEL=info
`;
}

// ─── Docker Compose Generator ────────────────────────────────────────────────

export function generateDockerCompose(config: InstallerConfig): string {
  const services: string[] = [];

  // App service
  services.push(`  app:
    build: .
    container_name: ${config.projectName || "shadowchat"}-app
    restart: unless-stopped
    ports:
      - "${config.port || 3000}:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://shadowchat:\${DB_PASSWORD}@db:3306/shadowchat
      - REDIS_URL=redis://:\${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=\${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
      ${config.enableRedis ? "redis:\n        condition: service_healthy" : ""}
    volumes:
      - ./logs:/app/logs
    networks:
      - shadowchat-net`);

  // Database service
  services.push(`  db:
    image: mysql:8.0
    container_name: ${config.projectName || "shadowchat"}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: \${DB_PASSWORD}
      MYSQL_DATABASE: shadowchat
      MYSQL_USER: shadowchat
      MYSQL_PASSWORD: \${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shadowchat-net`);

  // Redis service
  if (config.enableRedis) {
    services.push(`  redis:
    image: redis:7-alpine
    container_name: ${config.projectName || "shadowchat"}-redis
    restart: unless-stopped
    command: redis-server --requirepass \${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "\${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shadowchat-net`);
  }

  // Nginx service
  if (config.enableNginx) {
    services.push(`  nginx:
    image: nginx:alpine
    container_name: ${config.projectName || "shadowchat"}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - app
    networks:
      - shadowchat-net`);
  }

  return `version: "3.9"

services:
${services.join("\n\n")}

volumes:
  db-data:
  redis-data:
  nginx-cache:

networks:
  shadowchat-net:
    driver: bridge
`;
}

// ─── Nginx Config Generator ───────────────────────────────────────────────────

export function generateNginxConfig(config: InstallerConfig): string {
  const domain = config.domain || "localhost";
  const ssl = config.enableSSL;

  return `events {
  worker_connections 1024;
}

http {
  upstream shadowchat_app {
    server app:${config.port || 3000};
    keepalive 32;
  }

  # Rate limiting
  limit_req_zone $binary_remote_addr zone=api:10m rate=100r/m;
  limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/m;

  ${ssl ? `server {
    listen 80;
    server_name ${domain};
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl http2;
    server_name ${domain};

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;` : `server {
    listen 80;
    server_name ${domain};`}

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy strict-origin-when-cross-origin;

    # Gzip
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    location /api/trpc {
      limit_req zone=api burst=20 nodelay;
      proxy_pass http://shadowchat_app;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/oauth {
      limit_req zone=auth burst=5 nodelay;
      proxy_pass http://shadowchat_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      proxy_pass http://shadowchat_app;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
`;
}

// ─── Install Script Generator ─────────────────────────────────────────────────

export function generateInstallScript(config: InstallerConfig): string {
  return `#!/bin/bash
# ShadowChat / SKYCOIN4444 — 1-Click Server Installer
# Generated by Server Installer Engine
# Run as: sudo bash install.sh

set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║     ShadowChat / SKYCOIN4444 — Server Installer         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
echo "→ Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { echo "Docker not found. Installing..."; curl -fsSL https://get.docker.com | sh; }
command -v docker-compose >/dev/null 2>&1 || { echo "docker-compose not found. Installing..."; pip3 install docker-compose; }

# ── Clone / Update ────────────────────────────────────────────────────────────
echo "→ Setting up project directory..."
mkdir -p /opt/shadowchat && cd /opt/shadowchat

# ── Environment ───────────────────────────────────────────────────────────────
echo "→ Generating environment configuration..."
if [ ! -f .env ]; then
  cp .env.example .env
  echo "  ✓ .env created from template"
  echo "  ⚠ Please edit /opt/shadowchat/.env with your credentials before continuing"
  echo "  Press Enter to continue after editing..."
  read
fi

# ── Build & Start ─────────────────────────────────────────────────────────────
echo "→ Building Docker images..."
docker-compose build --no-cache

echo "→ Starting services..."
docker-compose up -d

# ── Database Migration ────────────────────────────────────────────────────────
echo "→ Running database migrations..."
sleep 10  # Wait for DB to be ready
docker-compose exec app pnpm db:push

# ── Health Check ──────────────────────────────────────────────────────────────
echo "→ Running health checks..."
sleep 5
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${config.port || 3000}/api/health)
if [ "$HTTP_STATUS" = "200" ]; then
  echo "  ✓ App is healthy (HTTP 200)"
else
  echo "  ✗ App health check failed (HTTP $HTTP_STATUS)"
  docker-compose logs app
  exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✓ ShadowChat installed successfully!                   ║"
echo "║  → Access at: http://${config.domain || "localhost"}:${config.port || 3000}              ║"
echo "╚══════════════════════════════════════════════════════════╝"
`;
}

// ─── Health Checks ────────────────────────────────────────────────────────────

export async function runHealthChecks(): Promise<HealthCheckResult[]> {
  const results: HealthCheckResult[] = [];
  const start = Date.now();

  // App health
  results.push({
    service: "App Server",
    status: "healthy",
    latency: Date.now() - start,
    message: "Express server running",
  });

  // DB health
  try {
    const dbStart = Date.now();
    await import("./db").then(({ db }) => db.execute("SELECT 1"));
    results.push({
      service: "Database",
      status: "healthy",
      latency: Date.now() - dbStart,
      message: "MySQL connection OK",
    });
  } catch (e) {
    results.push({
      service: "Database",
      status: "down",
      latency: 0,
      message: String(e),
    });
  }

  return results;
}
